### ISSUE TITLE
Creating Delete Button in order to delete Tasks/Notes

### ISSUE THREAD

**Issue by Jay2006sawant** [Polaris-School-of-Technology/Personal-Management-Dashboard#30] opened 2024-12-06 11:21 UTC
Uploading Personal Management Dashboard - Personal - Microsoft​ Edge 2024-12-06 16-37-11.mp4…

The above video clearly demonstrates the issues

- I can easily add Tasks/Notes. However, when it comes to removing the same; it lacks
-  expect the task or note to be removed from the list when the delete button is clicked.

### Approach To Be Used

1. In order to add Delete Button for tasks and Notes, I need to first update my html file by creating Delete button for task and notes
2. Styling the button using CSS for a consistent look
3. Implementing JavaScript functionality to handle the delete action by removing the task or note element from the DOM when the button is clicked.

**Comment by rahat2134** [comment] 2024-12-10 08:08
This is the duplicate of #10.

Before raising any issue take a look to existing one's. It's quite a daunting task for me to close issues again and again.
Plus it is a good practice to check the existing issues. It will help you in a long run.

**Closed by rahat2134** 2024-12-10 08:08 UTC
