### ISSUE TITLE
Add functionality to save input data to local storage using localStorage.setItem

### ISSUE THREAD

**Issue by Shivadharushni-M** [Polaris-School-of-Technology/Personal-Management-Dashboard#81] opened 2024-12-13 14:09 UTC
Currently, notes disappear when the page is refreshed. Modify the app to store notes in the browser's LocalStorage, so they persist even after a page reload.

Changes Made:
1. Added LocalStorage Integration:
Introduced functionality to store and retrieve notes using LocalStorage.
Implemented two helper functions:
saveNotesToLocalStorage: Saves the current list of notes to LocalStorage.
loadNotesFromLocalStorage: Retrieves saved notes from LocalStorage and displays them on page load.

2.Updated Note-Saving Logic:
Modified the event listener for the "Save Note" button to include a call to saveNotesToLocalStorage. This ensures notes are stored persistently every time a new note is added.
Page Load Functionality:

Added a DOMContentLoaded event listener to load saved notes from LocalStorage when the page is refreshed, making the notes persist across sessions.

Previously, notes disappeared when the page was refreshed due to the lack of persistent storage. By integrating LocalStorage, the notes now remain intact even after a page reload.

![Screenshot 2024-12-08 200613](https://github.com/user-attachments/assets/2f764cbf-44e6-4c19-9efa-d4cb7980fe6c)
![Screenshot 2024-12-08 200705](https://github.com/user-attachments/assets/f0f3621d-be99-4700-83c7-9603cd4477f8)

After the code implementation:-

https://github.com/user-attachments/assets/642376ea-9e97-48f0-9613-49c4cf5e9a07

@Rahat-CP please assign me this issue

**Comment by rahat2134** [comment] 2024-12-16 11:14
This is the duplicate of https://github.com/Polaris-School-of-Technology/Personal-Management-Dashboard/issues/57

**Closed** 2024-12-16 11:14 UTC
